authors = ["Andy Ferris <ferris.andy@gmail.com>"]
name = "TypedTables"
uuid = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
version = "1.0.0"

[deps]
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
Tables = "f31cc48a-97c4-11e8-115d-f1beebab189a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]