# See the mkdocs user guide for more information on these settings.
#   http://www.mkdocs.org/user-guide/configuration/

site_name:        TypedTables.jl
repo_url:         https://github.com/FugroRoames/TypedTables.jl
site_description: TypedTables - simple, columnar storage for Julia
site_author:      Andy Ferris

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Table types:
    - Table: man/table.md
    - FlexTable: man/flextable.md
  - Basic data manipulation:
    - Mapping data: man/map.md
    - Finding data: man/filter.md
    - Reducing data: man/reduce.md
  - Grouping and joining data:
    - Groupind data: man/group.md
    - Joining data: man/group.md
  - Storing and representing data:
    - Data representation: man/data.md
    - Acceleration indices: man/acceleratedarrays.md
    - Input and output: man/io.md
